---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: busser

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[spartan_loggly_rsyslog::default]
    attributes:
      loggly:
        token: test_token
        tags:
          - Vagrant
          - test
        log_files:
          - filename: /tmp/test.log
